### ISSUE TITLE
MENACE success graph

### ISSUE THREAD

**Issue by philip-kimber** [philip-kimber/MENACE#2]
I just wanted to point out how I planned for the graph to work, because some aspects of that code are already in.

The graph that most MENACE implementations use is one of `number of games played` (x-axis) against `change in number of beads in first box` (y-axis). This allows the user to see it learning without dwelling on the fact that it actually rarely wins.

This is facilitated by the menace.py `Menace.beads_over_time` list which is a list with one entry for each game played, of the number of beads at the end of that game. This can (almost) be a list of y-values and the index the x-value, except for the fact that the first entry of this list is after the first game - needs an origin value.

Once the graph is established, at the end of each `play_game` call (of whatever type, simulation, game etc), there will need to be a call to some kind of `Menace.update_graph()` function.

**Comment by scorbett123** [comment]
Yea, I was thinking for their to be some kind of command to manage what the graph is saying. For example win / loss / draw, or change in number of beads. This would allow us to originally show one aspect of it learning and then as it starts to win more games to switch it over to wins.

Or have it cycling through different graphs (I don't know whether this is possible).

**Comment by philip-kimber** [comment]
That is a good idea, if possible

**Comment by scorbett123** [comment]
It's probably going to take me until tomorrow until I can get this working, just realized that intellij was doing something for me that I wasn't expecting, if you want to commit any code I can merge them, so don't hold back on creating anything.

**Comment by philip-kimber** [comment]
Thanks for working on this. No problem. I might start working on the bead update thing soon and that won't take too long.

**Comment by scorbett123** [comment]
ok, yea, think the easiest way for me to fix my problem is create a tkinter window, matplotlib's system of keeping the same plot and just updating it seems really dodgy, and to hardly work at points, although its probably just me misunderstanding it. 

This will also make showing total wins, draws, and losses possible at the bottom.

**Comment by philip-kimber** [comment]
Sounds good if you can get it working. I have never used matplotlib to display anything other than a stationary, non-changing graph so it could well be the case that it isn't very good for this application.
